config/routes.rb
Rails.application.routes.draw do
  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  resources :users

  resources :estados

  resources :ambientes

  resources :elementos

  resources :tipo_elementos

  resources :registros

   root 'registros#index'

    resources :user_sessions
    resources :users

    get 'login' => 'user_sessions#new', :as => :login
    get 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/tipo_elemento.rb
class TipoElemento < ActiveRecord::Base
	has_many :elementos
	# Validar que los atributos sean obligatorios
	validates :nombre, :presence => true

	def self.search(search, page)
		where(['upper(nombre) like ?',
		"%#{search}%".upcase]).paginate(page: page).order("id")
	end

end

app/controllers/tipo_elementos_controller.rb
class TipoElementosController < ApplicationController
  before_action :set_tipo_elemento, only: [:show, :edit, :update, :destroy]

  # GET /tipo_elementos
  # GET /tipo_elementos.json
  def index
    @tipo_elementos = TipoElemento.search(params[:search], params[:page])
  end

  # GET /tipo_elementos/1
  # GET /tipo_elementos/1.json
  def show
  end

  # GET /tipo_elementos/new
  def new
    @tipo_elemento = TipoElemento.new
  end

  # GET /tipo_elementos/1/edit
  def edit
  end

  # POST /tipo_elementos
  # POST /tipo_elementos.json
  def create
    @tipo_elemento = TipoElemento.new(tipo_elemento_params)

    respond_to do |format|
      if @tipo_elemento.save
        format.html { redirect_to @tipo_elemento, notice: 'Tipo elemento fue creado con exito.' }
        format.json { render :show, status: :created, location: @tipo_elemento }
      else
        format.html { render :new }
        format.json { render json: @tipo_elemento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_elementos/1
  # PATCH/PUT /tipo_elementos/1.json
  def update
    respond_to do |format|
      if @tipo_elemento.update(tipo_elemento_params)
        format.html { redirect_to @tipo_elemento, notice: 'Tipo elemento fue actualizado con exito.' }
        format.json { render :show, status: :ok, location: @tipo_elemento }
      else
        format.html { render :edit }
        format.json { render json: @tipo_elemento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_elementos/1
  # DELETE /tipo_elementos/1.json
  def destroy
    @tipo_elemento.destroy
    respond_to do |format|
      format.html { redirect_to tipo_elementos_url, notice: 'Tipo elemento fue eliminado con exito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_elemento
      @tipo_elemento = TipoElemento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_elemento_params
      params.require(:tipo_elemento).permit(:nombre, :descripcion, :icono)
    end
end

app/helpers/tipo_elementos_helper.rb
module TipoElementosHelper
end

app/views/tipo_elementos/_tipo_elemento.html.erb
<div class="col-lg-2 col-md-4">
    <div class="panel panel-primary">
        <div class="panel-heading"> 
            <div class="row">
                <div class="col-xs-3">
                    <i class="fa <%= tipo_elemento.icono %>  fa-5x"></i>
                </div>
                <div class="col-xs-9 text-right">
                    <div class="huge"><%= Elemento.cuente(tipo_elemento.id)%></div>
                    <div><%= tipo_elemento.nombre %></div>
                </div>
            </div>
        </div>
        
        <div class="panel-footer">
            <a href=<%= tipo_elemento_path(tipo_elemento) %>>
                <div class="pull-right"><i class="fa fa-trash-o fa"></i>
                </div>
            </a>
           
            <a href=<%= edit_tipo_elemento_path(tipo_elemento)%>>
                <div class="pull-right"><i class="fa fa-edit"></i> 
                </div>
            </a>
            
            <a href=<%= elementos_path(tipo_elemento_id: tipo_elemento.id)%>>
                <span class="pull-left">Ir a <%= tipo_elemento.nombre %></span>
                <div class="clearfix"></div>
            </a>
        </div>
        
    </div>
</div>

app/views/tipo_elementos/edit.html.erb
<%- model_class = TipoElemento -%>
<div class="page-header">
  <h1>Editar <%= @tipo_elemento.nombre %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tipo_elementos/index.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Lending <small>Equipment</small>
            </h1>
            <ol class="breadcrumb">
                <center><li class="active">
                    <i class="fa fa-pied-piper-alt fa-5x"></i><h2> Bienvenidos</h2>
                </li></center>
            </ol>
        </div>
    </div>

     <ul><div class="btn-group">
        <%= link_to t('.new', :default => t("helpers.links.Agregar Tipo de Elemento")),
            new_tipo_elemento_path,
            :class => 'btn btn-success' %>
    </div></ul>

    
    <div class="row">
            <%= render  @tipo_elementos %>
    </div>
</div>    

app/views/tipo_elementos/new.html.erb
<%- model_class = TipoElemento -%>
<div class="page-header">
  <h1>Nuevo Tipo de Elemento</h1>
</div>
<%= render :partial => 'form' %>

app/views/tipo_elementos/show.html.erb
<%- model_class = TipoElemento -%>
<div class="page-header">
  <h1><%=t '.title', :default => @tipo_elemento.nombre %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nombre) %>:</strong></dt>
  <dd><%= @tipo_elemento.nombre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:descripcion) %>:</strong></dt>
  <dd><%= @tipo_elemento.descripcion %></dd>
  <dt><strong><%= model_class.human_attribute_name(:icono) %>:</strong></dt>
  <dd><%= @tipo_elemento.icono %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.Atras")),
              tipo_elementos_path, :class => 'btn btn-default'  %>
  <%= link_to t('.destroy', :default => t("helpers.links.Eliminar")),
              tipo_elemento_path(@tipo_elemento),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm",:default => 'Estas Seguro?')) },
              :class => 'btn btn-danger' %>
</div>