config/routes.rb
Rails.application.routes.draw do
  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  resources :users

  resources :estados

  resources :ambientes

  resources :elementos

  resources :tipo_elementos

  resources :registros

   root 'registros#index'

    resources :user_sessions
    resources :users

    get 'login' => 'user_sessions#new', :as => :login
    get 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/elemento.rb
class Elemento < ActiveRecord::Base
  belongs_to :tipo_elemento
  belongs_to :estado

  validates :nombre, :presence => true
  validates :codigo_interno, :presence => true
  validates :codigo_contable, :presence => true
  validates :tipo_elemento, :presence => true  
  validates :estado, :presence => true

  def self.search(search, page)
		where(['upper(codigo_interno) like ? or nombre = ?', 
		"%#{search}%".upcase,"#{search}"]).paginate(page: page).order("id")
	end

  def self.cuente(tipoelemt_id)
      Elemento.where(:tipo_elemento_id => tipoelemt_id).count
  end  

end

app/controllers/elementos_controller.rb
class ElementosController < ApplicationController
  before_action :set_elemento, only: [:show, :edit, :update, :destroy]

  # GET /elementos
  # GET /elementos.json
  def index
    tipo_elemento_id = params[:tipo_elemento_id]
    @elementos = Elemento.where(:tipo_elemento_id => tipo_elemento_id).search(params[:search], params[:page])
  end

  # GET /elementos/1
  # GET /elementos/1.json
  def show
  end

  # GET /elementos/new
  def new
    @elemento = Elemento.new
    @tipo_elemento_id = params[:tipo_elemento_id]
  end

  # GET /elementos/1/edit
  def edit
    @tipo_elemento_id = params[:tipo_elemento_id]
  end

  # POST /elementos
  # POST /elementos.json
  def create
    @elemento = Elemento.new(elemento_params)

    respond_to do |format|
      if @elemento.save
        format.html { redirect_to @elemento, notice: 'Elemento fue creado con exito.' }
        format.json { render :show, status: :created, location: @elemento }
      else
        format.html { render :new }
        format.json { render json: @elemento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /elementos/1
  # PATCH/PUT /elementos/1.json
  def update
    respond_to do |format|
      if @elemento.update(elemento_params)
        format.html { redirect_to @elemento, notice: 'Elemento fue actualizado con exito.' }
        format.json { render :show, status: :ok, location: @elemento }
      else
        format.html { render :edit }
        format.json { render json: @elemento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elementos/1
  # DELETE /elementos/1.json
  def destroy
    @elemento.destroy
    respond_to do |format|
      format.html { redirect_to elementos_url, notice: 'Elemento fue eliminado con exito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_elemento
      @elemento = Elemento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def elemento_params
      params.require(:elemento).permit( :nombre, :codigo_interno, :codigo_contable, :descripcion, :tipo_elemento_id, :estado_id)
    end
end

app/helpers/elementos_helper.rb
module ElementosHelper
end

app/views/elementos/_form.html.erb
<%= simple_form_for @elemento, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :nombre %>
  <%= f.input :codigo_interno %>
  <%= f.input :codigo_contable %>
  <%= f.input :descripcion %>
 <%= f.collection_select :tipo_elemento_id, TipoElemento.all, :id, :nombre, prompt: "Seleccione Tipo de Elemento", required: true %>
  <%= f.collection_select :estado_id, Estado.all, :id, :nombre, prompt: "Seleccione Estado" %>

  <div class="form-actions">
    <%= f.button :submit, "Guardar", :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.Cancelar")),
                elementos_path(tipo_elemento_id: @elemento.tipo_elemento_id), :class => 'btn btn-default' %>
  </div> 
<% end %>
 

app/views/elementos/edit.html.erb
<%- model_class = Elemento -%>
<div class="page-header">
  <h1>Editar <%= @elemento.nombre %></h1>
</div>
<%= render :partial => 'form' %>

app/views/elementos/index.html.erb
<%- model_class = Elemento -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">
    
    <%= form_tag elementos_path, :method => 'get' do %>
    <% content_tag :label do %>
    Buscar:
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Codigo Interno", :class => "btn btn-success"%>
    <% end %>
    <% end %>

  </div>

  <!-- Table -->
  <table class="table table-striped table-bordered ">
    <thead class="btn-success">
      <tr>
        <th>Mostrar Elemento</th>
        <th><%= model_class.human_attribute_name(:nombre) %></th>
        <th><%= model_class.human_attribute_name(:codigo_interno) %></th>
        <th>Placa Inventario</th>
        <th><%= model_class.human_attribute_name(:descripcion) %></th>
        <th><%= model_class.human_attribute_name(:tipo_elemento_id) %></th>
        <th><%= model_class.human_attribute_name(:estado_id) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>

  

    <tbody>
      <% @elementos.each do |elemento| %>
      <tr>
        <td><%= link_to "Mostrar Elemento", elemento_path(elemento) %></td>
        <td><%= elemento.nombre %></td>
        <td><%= elemento.codigo_interno %></td>
        <td><%= elemento.codigo_contable %></td>
        <td><%= elemento.descripcion %></td>
        <td><%= elemento.tipo_elemento.nombre %></td>
        <td><%= elemento.estado.nombre %></td>
        <td>
          <%= link_to'', edit_elemento_path(elemento,tipo_elemento_id: @tipo_elemento_id), :class => 'fa fa-edit fa-2x' %>
          <%= link_to '', elemento_path(elemento),:method => :delete,
          :data => { :confirm => 'Estas Seguro?'},
          :class => 'fa fa-trash-o fa-2x' %>
        </td>
      </tr>
      <% end %>
    </tbody>

    
  </table>
</div>

  

<%= link_to t('.new', :default => t("helpers.links.Nuevo")),
            new_elemento_path,
            :class => 'btn btn-primary' %>
<br>
Elementos: <%= @elementos.count %>

app/views/elementos/new.html.erb
<%- model_class = Elemento -%>
<div class="page-header">
  <h1>Nuevo <%= model_class %></h1>
</div>
<%= render :partial => 'form' %>

app/views/elementos/show.html.erb
<%- model_class = Elemento -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nombre) %>:</strong></dt>
  <dd><%= @elemento.nombre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:codigo_interno) %>:</strong></dt>
  <dd><%= @elemento.codigo_interno %></dd>
  <dt>Placa Inventario</strong></dt>
  <dd><%= @elemento.codigo_contable %></dd>
  <dt><strong><%= model_class.human_attribute_name(:descripcion) %>:</strong></dt>
  <dd><%= @elemento.descripcion %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tipo_elemento_id) %>:</strong></dt>
  <dd><%= @elemento.tipo_elemento.nombre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:estado_id) %>:</strong></dt>
  <dd><%= @elemento.estado.nombre %></dd>
</dl>

<div class="form-actions">
  <%= link_to 'Atras', elementos_path(tipo_elemento_id: @elemento.tipo_elemento_id), :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.Editar")),
              edit_elemento_path(@elemento), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.Eliminar")),
              elemento_path(@elemento),
              :method => 'delete',
              :data => { :confirm => 'Estas Seguro?' },
              :class => 'btn btn-danger' %>
</div>