config/routes.rb
Rails.application.routes.draw do
  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  resources :users

  resources :estados

  resources :ambientes

  resources :elementos

  resources :tipo_elementos

  resources :registros

   root 'registros#index'

    resources :user_sessions
    resources :users

    get 'login' => 'user_sessions#new', :as => :login
    get 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/registro.rb
class Registro < ActiveRecord::Base

  validates :documento, :presence => true
  validates :nombre_completo, :presence => true
  validates :numero_ficha, :presence => true
  validates :email, :presence => true

  # validar un atributo booleano
  validates :genero, inclusion: [true, false]

  # validarformato de un email
  validates :email, format:{ with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i,
  message: 'Formato no valido' }

  # Valida si un atributo es numerico
  validates :documento, numericality: true

	def self.search(search, page)
		where(['upper(documento) like ?  or numero_ficha = ?',
		"%#{search}%".upcase,"#{search}"]).paginate(page: page).order("id")
	end
end

app/controllers/registros_controller.rb
class RegistrosController < ApplicationController
  before_action :set_registro, only: [:show, :edit, :update, :destroy]

  # GET /registros
  # GET /registros.json
  def index
    @registros = Registro.search(params[:search], params[:page])
  end

  # GET /registros/1
  # GET /registros/1.json
  def show
  end

  # GET /registros/new
  def new
    @registro = Registro.new
  end

  # GET /registros/1/edit
  def edit
  end

  # POST /registros
  # POST /registros.json
  def create
    @registro = Registro.new(registro_params)

    respond_to do |format|
      if @registro.save
        format.html { redirect_to @registro, notice: 'Registro fue creado con exito.' }
        format.json { render :show, status: :created, location: @registro }
      else
        format.html { render :new }
        format.json { render json: @registro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registros/1
  # PATCH/PUT /registros/1.json
  def update
    respond_to do |format|
      if @registro.update(registro_params)
        format.html { redirect_to @registro, notice: 'Registro fue actualizado con exito.' }
        format.json { render :show, status: :ok, location: @registro }
      else
        format.html { render :edit }
        format.json { render json: @registro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registros/1
  # DELETE /registros/1.json
  def destroy
    @registro.destroy
    respond_to do |format|
      format.html { redirect_to registros_url, notice: 'Registro fue eliminado con exito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_registro
      @registro = Registro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def registro_params
      params.require(:registro).permit(:documento, :nombre_completo, :numero_ficha, :email, :genero)
    end
end

app/helpers/registros_helper.rb
module RegistrosHelper

	def mostrar_genero(genero)
     if genero
		"Masculino"
		else
		"Femenino"
	    end
	end
	
end

app/views/registros/_form.html.erb
<%= simple_form_for @registro, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :documento %>
  <%= f.input :nombre_completo %>
  <%= f.input :numero_ficha %>
  <%= f.input :email %>
  Masculino: <%= f.radio_button(:genero, true) %>
  Femenino: <%= f.radio_button(:genero, false) %>
  <div class="form-actions">
    <%= f.button :submit, 'Crear Registro', :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.Cancelar")),
                registros_path, :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/registros/edit.html.erb
<%- model_class = Registro -%>
<div class="page-header">
  <h1>Editar <%= model_class %></h1>
</div>
<%= render :partial => 'form' %>

app/views/registros/index.html.erb
 <%- model_class = Registro -%>
  <div class="page-header">
    <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  </div>

<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">

    <%= form_tag registros_path, :method => 'get' do %>
    <% content_tag :label do %>
    Buscar:
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Ficha o documento", :class => "btn btn-success" %>
    <% end %>
    <% end %>
  </div>

  <table class="table table-striped table-bordered  ">

    <thead class="btn-success">
      <tr> 
        <th>Mostrar Registro</th>
        <th><%= model_class.human_attribute_name(:documento) %></th>
        <th><%= model_class.human_attribute_name(:nombre_completo) %></th>
        <th><%= model_class.human_attribute_name(:numero_ficha) %></th>
        <th><%= model_class.human_attribute_name(:email) %></th>
        <th><%= model_class.human_attribute_name(:genero) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>


    <tbody>
      <% @registros.each do |registro| %>
        <tr>
          <td><%= link_to "Mostrar Registro", registro_path(registro) %></td>
          <td><%= registro.documento %></td>
          <td><%= registro.nombre_completo %></td>
          <td><%= registro.numero_ficha %></td>
          <td><%= registro.email %></td>
          <td><%= mostrar_genero(registro.genero) %></td>
          <td>
            <%= link_to '', edit_registro_path(registro), :class => 'fa fa-edit fa-2x' %>

            <%= link_to '', registro_path(registro),
                        :method => :delete,
                        :data => { :confirm => 'Estas Seguro?' },
                        :class => 'fa fa-trash-o fa-2x' %>
          </td>
        </tr>
      <% end %>
    </tbody>
</table>
</div>

<%= link_to t('.new', :default => t("helpers.links.Nuevo")),
            new_registro_path,
            :class => 'btn btn-primary' %>

<%= will_paginate @registros, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente &raquo;' %>
<br>
Registros: <%= @registros.count %>

app/views/registros/new.html.erb
<%- model_class = Registro -%>
<div class="page-header">
  <h1>Nuevo <%= model_class %></h1>
</div>
<%= render :partial => 'form' %>

app/views/registros/show.html.erb
<%- model_class = Registro -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:documento) %>:</strong></dt>
  <dd><%= @registro.documento %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nombre_completo) %>:</strong></dt>
  <dd><%= @registro.nombre_completo %></dd>
  <dt><strong><%= model_class.human_attribute_name(:numero_ficha) %>:</strong></dt>
  <dd><%= @registro.numero_ficha %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @registro.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:genero) %>:</strong></dt>
  <dd><%= mostrar_genero(@registro.genero) %></dd>
</dl>

<div class="form-actions">
  <%= link_to '',registros_path, :class => ' fa-reply fa-2x'  %>
  <%= link_to '',edit_registro_path(@registro), :class => 'fa fa-edit fa-2x' %>
  <%= link_to '', registro_path(@registro),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Estas Seguro?')) },
              :class => 'fa fa-trash-o fa-2x' %>
</div>